server.port=8080
spring.datasource.url=jdbc:postgresql://inventory-order:5432/inventory-service
spring.datasource.username=userr
spring.datasource.password=password
eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka