server.port=8082
spring.datasource.url=jdbc:postgresql://postgres:5432/inventory-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=userr
spring.datasource.password=password
eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka